"""SAGI Candidate Generator & Mutation Radius Module.

Implements candidate generation, temperature control, mutation radius,
and failure memory tracking for the SAGI core simulator.
"""

import hashlib
import json
import random
import time
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from sage.experimental.sagi.state import SAGIState


class CandidateProposal(BaseModel):
    """A candidate proposal generated by SAGI."""
    proposal_id: str
    parent_state_hash: str
    mutation_delta: Dict[str, Any]
    mutation_radius: float
    temperature: float
    persona_label: str = "default_agent"
    tier3_metadata: Dict[str, Any] = Field(default_factory=dict)
    timestamp: float = Field(default_factory=time.time)
    proposal_hash: str = ""

    def __init__(self, **data: Any):
        super().__init__(**data)
        if not self.proposal_hash:
            self.proposal_hash = self.compute_sha256()

    def compute_sha256(self) -> str:
        """Compute SHA-256 hash over semantic fields ONLY (ignoring tier3_metadata and persona_label)."""
        payload = {
            "proposal_id": self.proposal_id,
            "parent_state_hash": self.parent_state_hash,
            "mutation_delta": self.mutation_delta,
            "mutation_radius": round(self.mutation_radius, 4),
            "temperature": round(self.temperature, 4)
        }
        serialized = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


class SAGICandidateGenerator:
    """Candidate generator for SAGI Digital Twin Brain."""

    def __init__(self, seed: Optional[int] = 42):
        self.random = random.Random(seed)
        self.failure_memory: List[Dict[str, Any]] = []

    def record_failure(
        self,
        proposal: Optional[CandidateProposal] = None,
        failure_reason: str = "FAILED_EXECUTION",
        proposal_hash: Optional[str] = None,
        mutation_delta: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Record a failed candidate proposal or learning signal in failure memory."""
        pid = proposal.proposal_id if proposal else f"fail_{len(self.failure_memory)+1}"
        phash = proposal.proposal_hash if proposal else (proposal_hash or f"hash_fail_{len(self.failure_memory)+1}")
        delta = proposal.mutation_delta if proposal else (mutation_delta or {})

        record = {
            "proposal_id": pid,
            "proposal_hash": phash,
            "mutation_delta": delta,
            "failure_reason": failure_reason,
            "timestamp": time.time()
        }
        self.failure_memory.append(record)

    def is_known_failure(self, mutation_delta: Dict[str, Any]) -> bool:
        """Check if mutation delta matches a previously recorded failure."""
        for record in self.failure_memory:
            if record.get("mutation_delta") == mutation_delta:
                return True
        return False

    def generate_candidate(
        self,
        current_state: SAGIState,
        proposal_id_prefix: str = "cand",
        persona_label: str = "default_agent",
        tier3_metadata: Optional[Dict[str, Any]] = None
    ) -> CandidateProposal:
        """Generate a candidate proposal governed by current temperature and mutation radius."""
        temp = max(0.01, min(2.0, current_state.temperature))
        radius = max(0.001, min(1.0, current_state.mutation_radius))

        # Generate mutation delta within bounded radius
        base_val = round(self.random.uniform(-radius, radius), 4)
        mutation_delta = {
            "parameter_shift": base_val,
            "confidence_delta": round(base_val * temp, 4),
            "hypothesis_key": f"hyp_{self.random.randint(100, 999)}"
        }

        # Non-repeating failure check: adjust delta if previously failed
        attempts = 0
        while self.is_known_failure(mutation_delta) and attempts < 10:
            attempts += 1
            adjusted_val = round(base_val + (attempts * 0.05), 4)
            mutation_delta["parameter_shift"] = adjusted_val

        proposal_id = f"{proposal_id_prefix}_{current_state.cycle_index}_{self.random.randint(1000, 9999)}"

        proposal = CandidateProposal(
            proposal_id=proposal_id,
            parent_state_hash=current_state.current_hash,
            mutation_delta=mutation_delta,
            mutation_radius=radius,
            temperature=temp,
            persona_label=persona_label,
            tier3_metadata=tier3_metadata or {}
        )
        return proposal
