"""SAGE Policy Enforcement Kernel (SPEK) v1.1 Compliance Engine."""

import hashlib
import json
import threading
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from sage.core.boundary import BoundaryEnforcer
from sage.core.models import RuleState, SpekReceipt


class ComplianceEngine:
    """Enforces rule state transitions and maintains immutable audit ledgers.

    Saves validations to spek_vault.json, promotions to promotion_queue.log,
    and rejections to negative_results.json using thread-safe, atomic operations.
    """

    def __init__(
        self,
        vault_path: Optional[str | Path] = None,
        promotion_path: Optional[str | Path] = None,
        rejection_path: Optional[str | Path] = None,
        boundary_enforcer: Optional[BoundaryEnforcer] = None,
    ):
        """Initialize ComplianceEngine."""
        self.vault_path = Path(vault_path or ".sage/validation/audit/spek_vault.json")
        self.promotion_path = Path(promotion_path or ".sage/validation/audit/promotion_queue.log")
        self.rejection_path = Path(rejection_path or ".sage/validation/audit/negative_results.json")
        self.enforcer = boundary_enforcer or BoundaryEnforcer()

        self._lock = threading.Lock()
        self.vault: List[SpekReceipt] = []
        self._load_vault()

    def _load_vault(self) -> None:
        """Load vault ledger from disk."""
        if not self.vault_path.exists():
            self.vault = []
            return

        try:
            with open(self.vault_path, "r") as f:
                raw = json.load(f)
                if isinstance(raw, list):
                    self.vault = [SpekReceipt(**item) for item in raw]
        except Exception:
            self.vault = []

    def compute_receipt_hash(self, receipt: SpekReceipt) -> str:
        """Deterministically compute the SHA-256 hash of a receipt, excluding the receipt_hash itself."""
        data = receipt.model_dump()
        data.pop("receipt_hash", None)
        serialized = json.dumps(data, sort_keys=True)
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()

    def get_last_receipt_hash(self) -> str:
        """Get the hash of the last receipt in the append-only vault."""
        if not self.vault:
            return "0" * 64
        return self.compute_receipt_hash(self.vault[-1])

    def validate_transition(self, current: RuleState, target: RuleState) -> bool:
        """Determine if a state transition is permitted in the SPEK rule lifecycle.

        Allowed transitions:
        - PROPOSED -> EVALUATED
        - EVALUATED -> VALIDATED
        - VALIDATED -> APPROVED
        - VALIDATED -> REJECTED
        - APPROVED -> ARCHIVED
        - REJECTED -> ARCHIVED

        Args:
            current: Current state.
            target: Target state.

        Returns:
            True if permitted, False otherwise.
        """
        allowed = {
            RuleState.PROPOSED: {RuleState.EVALUATED},
            RuleState.EVALUATED: {RuleState.VALIDATED},
            RuleState.VALIDATED: {RuleState.APPROVED, RuleState.REJECTED},
            RuleState.APPROVED: {RuleState.ARCHIVED},
            RuleState.REJECTED: {RuleState.ARCHIVED},
            RuleState.ARCHIVED: set(),
        }

        return target in allowed.get(current, set())

    def append_receipt(
        self,
        receipt_id: str,
        proposal_id: str,
        state: RuleState,
        execution_permission: bool,
        authority_integrity_score: float,
        hdg_trace: List[Dict[str, Any]],
        signature: str,
        timestamp: str,
        auth_token: str,
    ) -> SpekReceipt:
        """Construct, sign, and append a new audit receipt to the vault.

        Args:
            receipt_id: ID of the receipt.
            proposal_id: ID of the rule proposal.
            state: Lifecycle state.
            execution_permission: True if action is allowed.
            authority_integrity_score: Score rating authority.
            hdg_trace: List of node structures from HDG causality path.
            signature: Signature generated by the attestation provider.
            timestamp: The timestamp utilized during signing.
            auth_token: Present security token.

        Returns:
            The generated SpekReceipt.
        """
        with self._lock:
            # Enforce boundary check
            self.enforcer.validate_mutation(self.vault_path, auth_token)

            prev_hash = self.get_last_receipt_hash()

            receipt = SpekReceipt(
                receipt_id=receipt_id,
                proposal_id=proposal_id,
                timestamp=timestamp,
                lifecycle_state=state.value,
                execution_permission=execution_permission,
                authority_integrity_score=authority_integrity_score,
                hdg_trace=hdg_trace,
                attestation_signature=signature,
                receipt_hash="",  # placeholder
                previous_receipt_hash=prev_hash,
            )

            # Compute actual deterministic receipt hash
            receipt.receipt_hash = self.compute_receipt_hash(receipt)

            self.vault.append(receipt)
            self._save_vault(auth_token)
            return receipt

    def _save_vault(self, auth_token: str) -> None:
        """Atomic write of the vault array to the disk."""
        self.enforcer.validate_mutation(self.vault_path, auth_token)

        temp_path = self.vault_path.parent / f"{self.vault_path.name}_{uuid.uuid4().hex}.tmp"
        try:
            serialized_vault = [r.model_dump() for r in self.vault]
            with open(temp_path, "w") as f:
                json.dump(serialized_vault, f, indent=2)
            temp_path.replace(self.vault_path)
        except OSError as e:
            if temp_path.exists():
                temp_path.unlink()
            raise IOError(f"Failed to atomically persist SPEK vault: {e!s}")

    def promote_candidate(self, proposal_id: str, title: str, auth_token: str) -> None:
        """Append an approved candidate's promotion metadata to the queue log.

        Uses a thread-safe append.

        Args:
            proposal_id: Approved proposal ID.
            title: Title of rule.
            auth_token: Present security token.
        """
        with self._lock:
            self.enforcer.validate_mutation(self.promotion_path, auth_token)

            ts = datetime.now(timezone.utc).isoformat()
            log_line = f"[{ts}] PROMOTED RULE proposal_id={proposal_id} title={title}\n"

            try:
                with open(self.promotion_path, "a") as f:
                    f.write(log_line)
            except OSError as e:
                raise IOError(f"Failed to write promotion entry: {e!s}")

    def log_rejection(self, proposal_id: str, reason: str, auth_token: str) -> None:
        """Persist a rejection entry to negative_results.json.

        Uses thread-safe, atomic writing.

        Args:
            proposal_id: Rejected proposal ID.
            reason: Reason description.
            auth_token: Present security token.
        """
        with self._lock:
            self.enforcer.validate_mutation(self.rejection_path, auth_token)

            # Load negative results
            results = []
            if self.rejection_path.exists():
                try:
                    with open(self.rejection_path, "r") as f:
                        results = json.load(f)
                        if not isinstance(results, list):
                            results = []
                except Exception:
                    results = []

            ts = datetime.now(timezone.utc).isoformat()
            results.append({
                "proposal_id": proposal_id,
                "timestamp": ts,
                "status": "REJECTED",
                "reason": reason,
            })

            temp_path = self.rejection_path.parent / f"{self.rejection_path.name}_{uuid.uuid4().hex}.tmp"
            try:
                with open(temp_path, "w") as f:
                    json.dump(results, f, indent=2)
                temp_path.replace(self.rejection_path)
            except OSError as e:
                if temp_path.exists():
                    temp_path.unlink()
                raise IOError(f"Failed to record rejection entry: {e!s}")

    def verify_vault_integrity(self, attestation_provider) -> bool:
        """Traverse the append-only ledger and verify the chain of receipt hashes and signatures.

        Args:
            attestation_provider: CryptographicAttestationProvider instance.

        Returns:
            True if the ledger is perfectly validated, False otherwise.
        """
        with self._lock:
            # Re-read vault to guarantee we have the latest state
            self._load_vault()

            if not self.vault:
                return True

            expected_prev_hash = "0" * 64

            for receipt in self.vault:
                # 1. Back-link validation
                if receipt.previous_receipt_hash != expected_prev_hash:
                    return False

                # 2. Receipt Hash verification
                if receipt.receipt_hash != self.compute_receipt_hash(receipt):
                    return False

                # 3. Verify cryptographic signature of the receipt metadata
                signing_payload = {
                    "receipt_id": receipt.receipt_id,
                    "proposal_id": receipt.proposal_id,
                    "timestamp": receipt.timestamp,
                    "lifecycle_state": receipt.lifecycle_state,
                    "execution_permission": receipt.execution_permission,
                    "authority_integrity_score": receipt.authority_integrity_score,
                    "hdg_trace": receipt.hdg_trace,
                }
                if not attestation_provider.verify(signing_payload, receipt.attestation_signature):
                    return False

                # Set next expected prev_hash
                expected_prev_hash = receipt.receipt_hash

            return True
