#!/usr/bin/env python3
"""SAGE ACT-PROD Real Archive Consumer Validation Runner.

Exercises the ACT-PROD operator dashboard against actual, freshly persisted
SAGE ArchiveEntry traces generated by executing real workspace revalidations.
"""

import os
import json
import shutil
from pathlib import Path

from sage.experimental.mission_control_bridge import SAGEMissionExecutionBridge
from sage.experimental.act.act_prod_dashboard import SAGEActProdDashboard


def run_real_consumer_validation():
    print("[*] SAGE ACT-PROD Real Archive Consumer Validation starting...")

    # Define actual production directories
    archive_dir = Path("sage_data/archive")
    registry_file = Path("evidence_capture/operational_capability_registry.json")

    # 1. Clean existing archive folder to ensure we begin from a known baseline
    if archive_dir.exists():
        shutil.rmtree(archive_dir)
    archive_dir.mkdir(parents=True, exist_ok=True)

    # 2. Instantiate the bridge pointing to production registry and archive
    bridge = SAGEMissionExecutionBridge(registry_path=str(registry_file), archive_path=str(archive_dir))

    # 3. Execute real revalidation workload for 2 targets with mock linter passes
    print("[*] Executing revalidation trace 1...")
    res1 = bridge.execute_revalidation_workload(
        mission_id="reval_prod_mission_1",
        target_files=["sage/change_impact.py"],
        run_real_lint=False
    )
    print(f"[+] Trace 1 overall success: {res1['overall_success']}")
    print(f"    Archived Entry ID: {res1.get('archived_entry_id')}")

    print("[*] Executing revalidation trace 2...")
    res2 = bridge.execute_revalidation_workload(
        mission_id="reval_prod_mission_2",
        target_files=["tests/test_change_impact.py"],
        run_real_lint=False
    )
    print(f"[+] Trace 2 overall success: {res2['overall_success']}")
    print(f"    Archived Entry ID: {res2.get('archived_entry_id')}")

    # 4. Instantiate the ACT-PROD operator dashboard
    dashboard = SAGEActProdDashboard(archive_path=str(archive_dir))

    # 5. Retrieve high-level summary and verify fields
    print("[*] Consuming summary data via SAGEActProdDashboard...")
    summary = dashboard.retrieve_operator_summary()

    print("\n" + "="*50)
    print("      SAGE ACT-PROD OPERATOR DASHBOARD SUMMARY")
    print("="*50)
    print(f"Total Archived Traces: {summary['total_archived_traces']}")
    metrics = summary["revalidation_metrics"]
    print(f"Missions Evaluated:   {metrics['total_missions_evaluated']}")
    print(f"Missions Succeeded:   {metrics['successful_revalidations']}")
    print(f"Success Rate:         {metrics['success_rate_percent']:.1f}%")
    print(f"Unique Revalidated:   {metrics['unique_capabilities_revalidated']}")
    print("="*50 + "\n")

    # Assert correct summary parsing
    assert summary["total_archived_traces"] == 2
    assert metrics["total_missions_evaluated"] == 2
    assert metrics["successful_revalidations"] == 2

    # 6. Retrieve deep diagnostics for a mission
    print("[*] Consuming deep diagnostics for 'reval_prod_mission_1'...")
    diag = dashboard.retrieve_mission_diagnostics("reval_prod_mission_1")
    assert diag is not None
    assert diag["mission_id"] == "reval_prod_mission_1"
    assert diag["overall_success"] is True
    assert diag["final_state"] == "CLOSED"
    assert diag["validated_by"] == "SAGEMissionExecutionBridge"

    print("\n" + "="*50)
    print(f"     DEEP DIAGNOSTICS: reval_prod_mission_1")
    print("="*50)
    print(f"Archive Entry ID:  {diag['archive_entry_id']}")
    print(f"Overall Success:   {diag['overall_success']}")
    print(f"Validated By:      {diag['validated_by']}")
    print(f"Rules Applied:     {diag['rules_applied']}")
    print(f"Revalidated Caps:  {diag['revalidated_capabilities']}")

    print("\nTransition Steps:")
    for step in diag["transition_steps"]:
        print(f"  - {step['previous_state']} -> {step['target_state']}")

    print("\nWorkload Command Executions:")
    for wl in diag["workload_executions"]:
        print(f"  - Cmd:     {wl['command']}")
        print(f"    Success: {wl['success']}")
    print("="*50 + "\n")

    # 7. Scan and verify no corrupted files
    print("[*] Running corruption scanner on archive directory...")
    corrupt_report = dashboard.handle_corrupted_archive_data()
    print(f"[+] Status:          {corrupt_report['status']}")
    print(f"[+] Corrupt Count:   {corrupt_report['corrupted_count']}")
    assert corrupt_report["status"] == "ok"
    assert corrupt_report["corrupted_count"] == 0

    print("[+] SAGE ACT-PROD Real Archive Consumer Validation passed successfully!")


if __name__ == "__main__":
    run_real_consumer_validation()
