"""Core state models for the SAGE C2 Flight GPS."""

import hashlib
from dataclasses import dataclass, field
from enum import Enum
import time
from typing import Optional, Set


class AirspaceStatus(Enum):
    """Safety classification of a capability target space."""

    CLEAR = "CLEAR"
    SHARED = "SHARED"
    DEPENDENT = "DEPENDENT"
    OCCUPIED = "OCCUPIED"
    STALE = "STALE"


class FlightLifecycle(Enum):
    """Execution progress of a flight, independent from airspace safety."""

    PROPOSED = "PROPOSED"
    RESERVED = "RESERVED"
    ACTIVE = "ACTIVE"
    TESTING = "TESTING"
    RECONVERGING = "RECONVERGING"
    INTEGRATED = "INTEGRATED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ABANDONED = "ABANDONED"


class ObservabilityState(Enum):
    """Trust level of the control tower's telemetry view."""

    NOMINAL = "NOMINAL"
    DEGRADED = "DEGRADED"
    OFFLINE = "OFFLINE"


@dataclass
class OwnershipFingerprint:
    """Code and artifact boundaries claimed by a flight."""

    files: Set[str] = field(default_factory=set)
    modules: Set[str] = field(default_factory=set)
    symbols: Set[str] = field(default_factory=set)
    artifacts: Set[str] = field(default_factory=set)


@dataclass
class FlightManifest:
    """Observable state for a candidate or airborne flight."""

    flight_id: str
    capability_target: str
    base_sha: str
    ownership: OwnershipFingerprint = field(default_factory=OwnershipFingerprint)
    lifecycle: FlightLifecycle = FlightLifecycle.PROPOSED
    airspace: AirspaceStatus = AirspaceStatus.CLEAR
    session_id: str = "UNKNOWN"
    pr_number: Optional[int] = None
    is_mergeable: bool = True
    heartbeat_ttl_seconds: float = 120.0
    last_ping_utc: float = field(default_factory=time.time)

    def is_heartbeat_expired(self, now: Optional[float] = None) -> bool:
        """Return whether the flight has exceeded its heartbeat TTL."""
        current = time.time() if now is None else now
        return current - self.last_ping_utc > self.heartbeat_ttl_seconds

    def refresh_heartbeat(self, now: Optional[float] = None) -> None:
        """Refresh the flight ownership heartbeat."""
        self.last_ping_utc = time.time() if now is None else now


@dataclass
class GPSClearanceReceipt:
    """Immutable SHA-256 clearance receipt generated by Flight GPS observer."""

    receipt_id: str
    flight_id: str
    capability_target: str
    exact_head_sha: str
    airspace_status: str
    observability_state: str
    cleared: bool
    timestamp: float = field(default_factory=time.time)
    receipt_hash: str = ""

    def compute_hash(self) -> str:
        payload = f"{self.receipt_id}:{self.flight_id}:{self.capability_target}:{self.exact_head_sha}:{self.airspace_status}:{self.observability_state}:{self.cleared}:{self.timestamp}"
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def generate_clearance_receipt(
    flight_id: str,
    capability_target: str,
    exact_head_sha: str,
    airspace_status: AirspaceStatus | str,
    observability_state: ObservabilityState | str = ObservabilityState.NOMINAL,
) -> GPSClearanceReceipt:
    """Generate cryptographically bound Flight GPS clearance receipt."""
    air_val = airspace_status.value if isinstance(airspace_status, AirspaceStatus) else str(airspace_status)
    obs_val = observability_state.value if isinstance(observability_state, ObservabilityState) else str(observability_state)
    cleared = (air_val.upper() in ("CLEAR", "SHARED")) and (obs_val.upper() != "OFFLINE")

    receipt_id = f"gps-clearance-{flight_id}-{int(time.time() * 1000)}"
    receipt = GPSClearanceReceipt(
        receipt_id=receipt_id,
        flight_id=flight_id,
        capability_target=capability_target,
        exact_head_sha=exact_head_sha,
        airspace_status=air_val,
        observability_state=obs_val,
        cleared=cleared,
    )
    receipt.receipt_hash = receipt.compute_hash()
    return receipt
